### ISSUE TITLE
Shortcut as Ctrl+Space not working in Firefox 52

### ISSUE THREAD

**Issue by pintassilgo** [tapapax/firefox-fts#10]
The cause seems to be this:
https://hg.mozilla.org/integration/autoland/rev/927bfc865b55

**Comment by tapapax** [comment]
Thanks for you report! I believe that 5f666e will fix it while I'm preparing proper correction.
I've already uploaded it to AMO, waiting for their approvement now.

**Comment by pintassilgo** [comment]
For me this fixed only for about: pages (like the FTS options page). Normal tabs with sites loaded still don't work.

**Comment by tapapax** [comment]
Due to some reason FTS worked correctly on FF54 build where I tested it.
Now I have made one more fix - bc3eaa08d76770913ab8da2601ea88848e12cef0. That should help.

Queue Position: 210 of 210 :(

**Comment by pintassilgo** [comment]
Thank you, now it is working properly!

P.S.: not related to this issue, but since the first release (1.0.3), every time I install/update your extension it disables all shortcuts from other extensions until I restart Firefox.

**Comment by tapapax** [comment]
Version 1.0.11 with shortcut fix is approved at AMO now.

I'll try to fix that behavior you are talking about as soon as I'll get free a little.
