### ISSUE TITLE
Firefox quantum support

### ISSUE THREAD

**Issue by psilospore** [tapapax/firefox-fts#11]
Could you support firefox quantum

**Comment by epleterte** [comment]
This would be great! I can hardly live without this - I've been very happy with this plugin. I can't understand how people can live without things like this plugin, and I keep checking back hoping there's been an update/rewrite (if anybody know about a good replacement, I'd be grateful to hear about that too).

**Comment by tapapax** [comment]
Initial version of WebExtensions addon is now available. Please give your feedback if something is wrong :)
