### ISSUE TITLE
Shortcut for MAC - currently doesn't work

### ISSUE THREAD

**Issue by damikem** [tapapax/firefox-fts#12]

**Comment by tapapax** [comment]
Have you tried using Command+Space?

**Comment by damikem** [comment]
I tried, and it didn't work for me (maybe only for me?)

**Comment by tapapax** [comment]
Seems like Ctrl+Space and Command+Space are reserved combinations in Mac.
And I'm not sure which hotkey will be the best replacement for this OS. Maybe it is ok to wait until FF60 release and to support remapping hotkey by user.

**Comment by ehuss** [comment]
One workaround, you can go into System Preferences and disable (or change) the system Ctrl-Space shortcut (Keyboard > Shortcuts > Input Sources), which allows it to work in Firefox.

**Comment by damikem** [comment]
No need in workarounds! It is working 👍 
I call for closing this issue :)

**Comment by tapapax** [comment]
Also version 2.2.0 (already in AMO) have got hotkey options available.
