### ISSUE TITLE
An option to customize shortcut combination

### ISSUE THREAD

**Issue by damikem** [tapapax/firefox-fts#13]

**Comment by jscher2000** [comment]
Firefox 60 will allow extension developers to change the extension's default keyboard shortcut to another one. https://developer.mozilla.org/Add-ons/WebExtensions/API/commands/update

**Comment by damikem** [comment]
So it can now be utilized, right?

**Comment by jscher2000** [comment]
> So it can now be utilized, right?

Yes. (However, this is not my extension.)

**Comment by tapapax** [comment]
Version 2.2.0 (already in AMO) have got hotkey options available.
