### ISSUE TITLE
Don't load site icon for incognito tabs

### ISSUE THREAD

**Issue by jscher2000** [tapapax/firefox-fts#14]
To prevent private window site icons from being stored in the regular cache, it would be preferable not to load them in the popup. You could use null or with a little more work, replace them with a mask icon (https://design.firefox.com/icons/viewer/ in "General" category).

For example, in switcher.js, modifying line 20 as follows:

    19    $('<td></td>').append(
    20      tab.favIconUrl && (tab.incognito != true)
    21        ? $('<img width="16" height="16">')
    22            .attr('src', tab.favIconUrl)
    23        : null
    24    ),

(That's "air code")

Ref. https://discourse.mozilla.org/t/context-of-inline-image-requests-in-extension-page-e-g-a-popup/27932

**Comment by tapapax** [comment]
Thanks for the issue!
I have replaced favicon with the mask icon, as you suggested.
What does "air code" mean?

**Comment by tapapax** [comment]
2.1.0 is now available in AMO.

**Comment by jscher2000** [comment]
Thanks! 

"Air code" is like "air guitar" -- it looks like it should work, but it still needs to be proven out.
