### ISSUE TITLE
Support closing a selected tab

### ISSUE THREAD

**Issue by dmitry-timofeev** [tapapax/firefox-fts#19]
## Overview
Support closing a currently selected tab using a hot key (e.g., `Delete`).

**Comment by dmitry-timofeev** [comment]
@tapapax , 

I may try to implement this feature, if you are OK with it.

**Comment by tapapax** [comment]
@dmitry-timofeev it will be great.
I think we could [also] support `Ctrl+W` hotkey which is common for closing tabs. Not sure it is possible since browser already uses this combination.
