### ISSUE TITLE
Find terms out of order

### ISSUE THREAD

**Issue by pintassilgo** [tapapax/firefox-fts#2]
Should behave like address bar, matching tabs even if the terms (both title and URL) are out of order.

Example:

https://addons.mozilla.org/en-US/firefox/addon/fast-tab-switcher/
"add fas" should find the address above, if it's open.

**Comment by tapapax** [comment]
Thank you. Implemented improved search: 49b4179d59f7277547b6e9a6acdfd764e7125b6f
