### ISSUE TITLE
Wrong tab order in case of multiple windows

### ISSUE THREAD

**Issue by dmitry-timofeev** [tapapax/firefox-fts#28]
## Overview
The active tabs in different windows appear in a random order in the top of the list.

If there are several browser windows, the currently active tab in each window is reported as 'active' and 'highlighted', therefore, their 'lastAccessed' times are pretty close to each other and are not equal to the last time the corresponding _window_ was focused. As a result, the top N tabs are comprised of the current active tabs in N open browser windows in _random_ order. If, for example, one browser window is used actively whilst the other — not, the top of the tab list is still occupied by the active tabs from background windows.

### How to reproduce
1. Open _N_ browser windows with different active tabs (3-4 would be enough).
2. Open FTS extension several times, note the varying order of the top _N_ tabs.

**Comment by tapapax** [comment]
I'm not sure if there is an elegant solution for this, because browser doesn't provide us window last focus time.
One possibility is to track `windowId -> lastFocusedTime` map ourself in a background script via windows `onFocusChanged` and `onRemoved` events. Switcher popup can access this map through `runtime.sendMessage`. Finally, sort key for tab could be `max(tab.lastAccessTime, windowLastFocusedTime)` for active tabs.

**Comment by dmitry-timofeev** [comment]
That's unfortunate we can't get that from the browser directly.

I bumped into this issue when thought it would be cool to highlight not the top tab which is supposed to be the current active tab, but the second top tab which is the previously active tab (i.e., the one you are more likely to switch to). That would be the same behaviour as in "Recent Files" switcher in IntelliJ products. It works well in FTS if there is only a single browser window, but breaks if there are multiple.

**Comment by dmitry-timofeev** [comment]
Do you think changing the initially focused tab from the first to the second top tab is worth integrating before fixing this issue, as a separate feature? Only the single-windowed users might benefit from such a change.

**Comment by tapapax** [comment]
I don't think it is worth it, but anyway I'll be glad to merge this changes if you will decide to implement them. :)

> Only the single-windowed users might benefit

Implementation could also ensure that the first line in the list represents currently active tab (until it is filtered out). This measure will make this feature usefull not only for single-windowed users.

**Comment by tapapax** [comment]
may be fixed in 2.6.0 @ AMO

**Comment by dmitry-timofeev** [comment]
Brilliant, thank you!

> I bumped into this issue when thought it would be cool to highlight not the top tab which is supposed to be the current active tab, but the second top tab which is the previously active tab (i.e., the one you are more likely to switch to).

I must dig out that branch 😄

**Comment by dmitry-timofeev** [comment]
Submitted as #42.
