### ISSUE TITLE
Wide Permissions

### ISSUE THREAD

**Issue by matt9j** [tapapax/firefox-fts#30]
I would love to use this extension, but it requests really wide permissions that seem unnecessary. In the firefox add-ons registry, the extension is listed as requiring "Access your data for all websites". This includes password fields. Current versions of firefox support a permission level for "Read the text of all open tabs" according to https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions. This seems like it would be sufficient for search? Is there a technical reason why the all data permission is necessary?

I would be happy to try to provide a patch set, but have no experience developing firefox extensions so it might take me a little bit :smile:

**Comment by tapapax** [comment]
You are correct, <all_urls> permission is not required at all.
It is removed now in 2.5.1 version which is already at AMO.
Thanks for the issue! :)
