### ISSUE TITLE
cannot change hotkey on mac

### ISSUE THREAD

**Issue by chrishiestand** [tapapax/firefox-fts#37]
fts version 2.5.1
firefox: 65.0.1
MacOS Mojave

When I change the hotkey sequence from the default, close the add-on manager, and re-open, the hotkey sequence has reverted to the default. But setting "Automatic Updates" to "On" is remembered. 

Also the default hotkey behavior does not work on my system even though clicking on the tab switcher brings up the pop-up as expected. I hit command+control+space and it brings up the emoji symbols. But I'd prefer to not use the default hotkeys anyway.

**Comment by chrishiestand** [comment]
Also thanks for making this add-on, this should solve a significant time suck for me.

**Comment by tapapax** [comment]
Actually default popup combination is `Control+Space`, with no `Cmd` button involved - just tried this on MacOS.
However seems like there is an issue with `Cmd` checkbox **always** active in the preferences page. I have also tried setting i.e. `Control+G` hotkey and it wasn't reverted.
Could you try `Control+Space` combination and ignore `Cmd` checkbox while setting other hotkeys?

**Comment by tapapax** [comment]
Hotkey options are really buggy now, but in FF 66+ you will be able to use browser built-in "Manage Extension Shortcuts" command instead, which is much better and convenient :)

https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by chrishiestand** [comment]
Thanks @tapapax, you are correct about `Control+Space` in MacOS. I didn't try that because I've got the same hotkey attached to another global shortcut, but when I disabled that I do see it working properly as you say. I will look forward to trying FF66 :-)
