### ISSUE TITLE
Subsequent taps of Ctrl-Space moves down the list

### ISSUE THREAD

**Issue by charlesroper** [tapapax/firefox-fts#39]
It would be cool if, after opening with <kbd>Ctrl</kbd>+<kbd>Space</kbd>, subsequent taps of <kbd>Space</kbd> while <kbd>Ctrl</kbd> is still held moves the selection down the list and releasing makes the switch. Essentially the same behaviour as Windows' native <kbd>Alt</kbd>+<kbd>Tab</kbd> window switching and Firefox's <kbd>Ctrl</kbd>+<kbd>Tab</kbd> ([documented here](https://support.mozilla.org/en-US/kb/tab-preferences-and-settings)).

**Comment by tapapax** [comment]
Nice idea, I have implemented this in ca2d0cd.
Ctrl+Shilt+Space also moves the selection up.

**Comment by tapapax** [comment]
2.6.0 @ AMO

**Comment by charlesroper** [comment]
Sorry, I never said thank you for this. So **thank you!** 😄
