### ISSUE TITLE
slow with 20 tabs

### ISSUE THREAD

**Issue by rryan** [tapapax/firefox-fts#41]
Thanks a ton for the extension, and for making it Free software! 
I'm on Firefox 72.0.1 64-bit on macOS 10.14.6 on a 15" macbook pro.

The tab menu takes a few seconds to open when I only have 20 tabs open. Is that expected?

**Comment by tapapax** [comment]
Welcome!
Nope, this is not expected.
I've got a lot more tabs working fast enough with 72.0.1/64b.
Try to do some other things -
- filtering
- closing a tab via Ctrl+Delete (it will refresh tab list after)

Are these operations also slow?

**Comment by tapapax** [comment]
Closed due to inactivity.
