### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by sergeevabc** [tapapax/firefox-fts#5]
Dear Andrew,
Could you be so kind to consider making addon compatible with [Pale Moon](https://www.palemoon.org/) in the next release?

**Comment by tapapax** [comment]
Addon should work in Pale Moon now, you can load new version from
https://addons.mozilla.org/firefox/addon/fast-tab-switcher/

**Comment by sergeevabc** [comment]
I appreciate your help, @tapapax. God bless you.
